### ISSUE TITLE
Request: Sort Tasks By Priority

### ISSUE THREAD

**Issue by callumgwtaylor** [spoo-bar/code-with-todoist#19]
Thanks so much for this extension, I'm finding it really useful.

Is there a way to use the plugin that sorts tasks by their priority? At the moment it seems the default for me is alphabetical.

Thanks

**Comment by spoon611** [comment]
Currently the sorting is dependent on how the tasks are ordered in the Todoist app.
But I can try to add a setting which will override that and do priority based sorting

**Comment by spoo-bar** [comment]
@callumgwtaylor This feature is now available in v0.5.2.
I have added a setting `code.todoist.sortBy` to be able to choose how the Todoist tasks should be sorted in the task views. 

Thanks a lot for your feedback and patience

**Comment by callumgwtaylor** [comment]
Thanks!
