### ISSUE TITLE
Request: create new Todoist task from the IDE

### ISSUE THREAD

**Issue by ojoven** [spoo-bar/code-with-todoist#23]
I assumed that with the plugin we could not only see the tasks from Todoist but also to create new ones just from the IDE.
Is this something you're considering?

In any case, thanks for the plugin, it looks great!

**Comment by gaboceron10** [comment]
Yeah, this basic functionality would be nice.

**Comment by spoo-bar** [comment]
@ojoven @gaboceron10 
This feature is now available in v0.5.2.

![image](https://user-images.githubusercontent.com/9302666/128575523-0b7550b1-29c8-48dd-a9de-29ef33548d2d.png)
You can use the `Create Task` command or the icon on `Workspace Project` view to create a new Todoist task from the extension.
New Task is associated with the selected workspace project. If no workspace project is set, it is associated with `Inbox` project.

Thanks a lot for your feedback
