### ISSUE TITLE
Todoist Sync failed. Unknown error. Request failed with status code 410

### ISSUE THREAD

**Issue by noamsiegel** [spoo-bar/code-with-todoist#35]
**Describe the bug**
Sync not working despite the correct access token

**To Reproduce**
1. Download the extension
2. Insert the API token in the user settings JSON
3. Click refresh on the code-with-todoist sidebar plugin
4. See the error

**Expected behavior**
It should have loaded my todoist tasks

**Screenshots**
![image](https://user-images.githubusercontent.com/52804845/208846662-9f049cc2-d3b7-491e-b513-580eab42715e.png)

**vscode (please complete the following information):**
 - macOS Ventura

**Todoist (please complete the following information, if relevant):**
 - Todoist Premium user : yes

**Additional context**
N/A

**Comment by spoo-bar** [comment]
Thanks for letting me know!

This should be fixed in the latest release. `v1.1.1`
